### PR TITLE
6 create a dcatdistribution of the ontology for better indexing at tib ts

### PR DESCRIPTION
**Pull request by SArndt-TIB**

### CODE REVIEW

**Comment by SArndt-TIB** [comment]
@andrecastro0o Would you have the time to give thumbs up?

**Comment by andrecastro0o** [comment]
@SArndt-TIB !! :) happy to know that this project is being useful.
I was looking at the ttl and it looks good.
just to get it clear, you are creating new files inside distributions/ right? I think the downside of that approach is that it bypasses the pipeline described in https://github.com/tibonto/DFG-Fachsystematik-Ontology#createupdate-ontology
And i think the automated testing will not check that files in that folder, unless told to.

but you got my :+1:

**Comment by SArndt-TIB** [comment]
@andrecastro0o You are right, it should not be the case that I bypass the tests and pipeline. I will suggest something different. I would not normally provide a label from a different language as a synonym, though - I do that just for the sake of OLS.

**Comment by SArndt-TIB** [comment]
@andrecastro0o I updated the script for ontology creation so that German labels will be provided via skos:altLabel instead of rdfs:label. OLS should be able to work with that. Since your tests pass, I would be glad if you could have another look, and merge. I created a tag from main so the old version of the project can be properly be referred to. Thanks a lot!

**Pull request merged**
