### PR TITLE
17 align with gbv dfg2024

### LINKED ISSUE #17: Align with https://uri.gbv.de/terminology/dfg/
The DFG Fachsystematik (BARTOC record and URI http://bartoc.org/en/node/520) has already been converted to RDF/SKOS at https://github.com/gbv/jskos-data/tree/master/dfg with URI and namespace http://uri.gbv.de/terminology/dfg/  (*the URIs are currently not resolveable because the web application at https://uri.gbv.de/terminology/ is being worked on*). Both versions should be aligned.

Apart from the URIs, the version <https://uri.gbv.de/terminology/dfg/> uses SKOS, so each class is a `skos:Concept` and hierarchy uses `skos:broader`/`skos:narrower`. Furthermore notations are included with `skos:notation`.

### PR DESCRIPTION
**Pull request by andrecastro0o**
closes #17

### CODE REVIEW

**Comment by andrecastro0o** [comment]
OK so the owl:sameAs statements mapping each term to GBV dfg2024 are on script and TTL.

@nichtich & @SArndt-TIB  do you want to have a look at the [dfgo.ttl diff](https://github.com/tibonto/DFG-Fachsystematik-Ontology/pull/33/files#diff-18a7d400d756e57824dbcae97fa9639cf255f2bc86cd8d92422d9977793e7c7b)  and see if you agree with the mapping.

I used the full URI as I was not sure what prefix to use. If you have any suggestions let me know. Otherwise let's go with the URI.

Anything else we should mention about this mapping?

**Comment by SArndt-TIB** [comment]
@andrecastro0o Looks good to me. We have to be aware, that owl:sameAs is used to express a relation between individuals - that will cause a punning of our classes. Protege, for instance, will list all the classes as individuls, too. The same would happen with something like skos:exactMatch. We could prevent this by using a less strict property like rdfs:seeAlso.

I am not sure, what else to say about the mapping, right now.

**Comment by andrecastro0o** [comment]
> @andrecastro0o Looks good to me. We have to be aware, that owl:sameAs is used to express a relation between individuals - that will cause a punning of our classes. Protege, for instance, will list all the classes as individuls, too. The same would happen with something like skos:exactMatch. We could prevent this by using a less strict property like rdfs:seeAlso.
> 
> I am not sure, what else to say about the mapping, right now.

@SArndt-TIB thank you for the feedback.
I see what you mean. And weirdly the `owl:sameAs` in Protege, points each term to  



I tried the same with `skos:exactMatch` and the individuals are gone and it points to GBV DFG2024.
I'd prefer to go for `skos:exactMatch` or `skos:closeMatch`

Looking at their definitions in [skos-reference/#mapping](https://www.w3.org/TR/skos-reference/#mapping) I would say that `skos:closeMatch` is the most suited relation. ` skos:exactMatch` is not exactly true, as DFGO terms are classes and GBV DFG2024 are skos concepts, right?

> The property skos:closeMatch is used to link two concepts that are sufficiently similar that they can be used interchangeably in some information retrieval applications. In order to avoid the possibility of "compound errors" when combining mappings across more than two concept schemes, skos:closeMatch is not declared to be a transitive property.

> The property skos:exactMatch is used to link two concepts, indicating a high degree of confidence that the concepts can be used interchangeably across a wide range of information retrieval applications. skos:exactMatch is a transitive property, and is a sub-property of skos:closeMatch.



I don't think rdfs:seeAlso expresses a relation of similarity between these 2 sets of terms.

**Comment by andrecastro0o** [comment]
Also I will add an editor note to the metadata:

> DFGO is aligned with GBV DFG2024 via skos:closeMatch relations. The two semantic artifacts were developed separately, but both teams strive towards alignment. While DFGO defines terms as owl:Class instances, GBV defines them as skos:Concept. More details on GBV DFG2024 at http://uri.gbv.de/terminology/dfg/

Feel free to add any suggestions

**Comment by SArndt-TIB** [comment]
@andrecastro0o Thanks!

> I tried the same with skos:exactMatch and the individuals are gone and it points to GBV DFG2024.
I'd prefer to go for skos:exactMatch or skos:closeMatch

If you do not import skos, skos:exactMatch is likely interpreted as an annotation property (that's also causing the profile error). skos:exactMatch is an object property - when you import skos, the same as with owl:sameAs should happen. 

I agree that rdfs:seeAlso is too weak for a mapping. Using skos:closeMatch makes sense due to the reasons you name.

**Comment by andrecastro0o** [comment]
> > 
> 
> If you do not import skos, skos:exactMatch is likely interpreted as an annotation property (that's also causing the profile error). skos:exactMatch is an object property - when you import skos, the same as with owl:sameAs should happen.

thanks @SArndt-TIB I wasn't aware of it. a bit rusty on this ontology design details.
I did import skos `owl:imports skos: .` And no more Annotation errors from DFGO terms, but OWL 2 DL Profile Report is trowing errors related to dcterms, outside the scope of DFGO.

How to best deal with this :hankey: ? I am happy to ditch the DL-profile validation test. Or just use a seeAlso, but darn, this stuff is hard!

`robot validate-profile --profile DL --input dfgfo.ttl`

```
OWL 2 DL Profile Report: Ontology and imports closure NOT in profile. The following violations are present:
Use of undeclared annotation property: <http://purl.org/dc/terms/contributor> in annotation [Annotation(<http://purl.org/dc/terms/contributor> "Dave Beckett") in null]
Use of undeclared class: rdf:List [ObjectPropertyRange(<http://www.w3.org/2004/02/skos/core#memberList> rdf:List) in OntologyID(OntologyIRI(<http://www.w3.org/2004/02/skos/core>) VersionIRI(<null>))]
Use of undeclared annotation property: <http://purl.org/dc/terms/creator> in annotation [Annotation(<http://purl.org/dc/terms/creator> "Sean Bechhofer") in null]
Use of undeclared annotation property: <http://purl.org/dc/terms/contributor> in annotation [Annotation(<http://purl.org/dc/terms/contributor> "Participants in W3C's Semantic Web Deployment Working Group.") in null]
Use of undeclared annotation property: <http://purl.org/dc/terms/creator> in annotation [Annotation(<http://purl.org/dc/terms/creator> "Alistair Miles") in null]
Use of reserved vocabulary for class IRI: rdf:List [ObjectPropertyRange(<http://www.w3.org/2004/02/skos/core#memberList> rdf:List) in OntologyID(OntologyIRI(<http://www.w3.org/2004/02/skos/core>) VersionIRI(<null>))]
Use of undeclared annotation property: <http://purl.org/dc/terms/contributor> in annotation [Annotation(<http://purl.org/dc/terms/contributor> "Nikki Rogers") in null]
Use of undeclared annotation property: <http://purl.org/dc/terms/description> in annotation [Annotation(<http://purl.org/dc/terms/description> "An RDF vocabulary for describing the basic structure and content of concept schemes such as thesauri, classification schemes, subject heading lists, taxonomies, 'folksonomies', other types of controlled vocabulary, and also concept schemes embedded in glossaries and terminologies."@en) in null]
Use of undeclared annotation property: <http://purl.org/dc/terms/title> in annotation [Annotation(<http://purl.org/dc/terms/title> "SKOS Vocabulary"@en) in null]

PROFILE VIOLATION ERROR https://github.com/tibonto/dfgfo violates profile DL
For details see: http://robot.obolibrary.org/validate-profile#profile-violation-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

**Comment by SArndt-TIB** [comment]
@andrecastro0o Yeah, I see. Well, I added some quick fix, that avoids the "Rattenschwanz" of the import.

**Review by SArndt-TIB — APPROVED** [review]
Added some suggestions where we do not need to drop the profile check.

**Comment by andrecastro0o** [comment]
super @SArndt-TIB ! thank you. I will merge to main :)

**Pull request merged**
