### PR TITLE
#34 prepare release v. 2024

### PR DESCRIPTION
**Pull request by SArndt-TIB**
… copies of Systematik as pdf (since links are always broken)

### CODE REVIEW

**Review by andrecastro0o — APPROVED** [review]
all seems good @SArndt-TIB thanks for the corrections

**Comment by SArndt-TIB** [comment]
@andrecastro0o I added an rdf+xml serialization creation to the script - could you add the dfgfo.owl to the github actions?

**Comment by andrecastro0o** [comment]
@SArndt-TIB I have extended the tests to OWL. There are 2 reports that will be downloaded with the artifacts one for the TTL another for the OWL (see https://github.com/tibonto/DFG-Fachsystematik-Ontology/actions/runs/10598476701).

I also took the change to update the version of the github actions checkout and upload-artifact as there were some deprecation warnings popping up

**Comment by SArndt-TIB** [comment]
Hey, @andrecastro0o that sounds good. Thanks a lot!

**Pull request merged**
